name: ci
on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, "3.10", 3.11]
        os: [ubuntu-22.04, ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.4"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run test
        run: poetry run pytest
